In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
(np.ones(20)*2) ** (np.arange(20)+1) / (np.arange(20)+1)

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [32]:
np.sum((0.1**(3*np.arange(6))) * (0.2**(4*np.arange(6))))

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [39]:
A = np.zeros([8, 8])
A[::2,::2] = 1
A[1::2, 1::2] = 1
A

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [110]:
X = np.random.random((5, 2))
np.hstack((np.sum(X ** 2, axis = 1), np.arctan(X.T[0] / X.T[1]))).reshape(2,5).T

array([[0.75870172, 1.39328854],
       [0.31437907, 0.50329303],
       [0.97809497, 1.28223179],
       [0.2597326 , 0.15408147],
       [0.91877479, 1.28125865]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [36]:
X = np.random.random((10, 10))
row = np.argmax(X) // 10;
col = np.argmax(X) % 10;
row, col

(1, 6)

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [47]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

np.argmin(np.sum((X - y) ** 2, axis = 1))

7

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [121]:
def fun(val):
    if val < 0:
        return val**2 + 2 * val + 6
    elif val <=2:
        return val + 6
    else:
        return val**2 + 4 * val - 4

x = np.arange(-3, 3, 0.1)
funv = np.vectorize(fun)
funv(x)

array([ 9.  ,  8.61,  8.24,  7.89,  7.56,  7.25,  6.96,  6.69,  6.44,
        6.21,  6.  ,  5.81,  5.64,  5.49,  5.36,  5.25,  5.16,  5.09,
        5.04,  5.01,  5.  ,  5.01,  5.04,  5.09,  5.16,  5.25,  5.36,
        5.49,  5.64,  5.81,  6.  ,  6.1 ,  6.2 ,  6.3 ,  6.4 ,  6.5 ,
        6.6 ,  6.7 ,  6.8 ,  6.9 ,  7.  ,  7.1 ,  7.2 ,  7.3 ,  7.4 ,
        7.5 ,  7.6 ,  7.7 ,  7.8 ,  7.9 ,  8.  ,  8.81,  9.64, 10.49,
       11.36, 12.25, 13.16, 14.09, 15.04, 16.01])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [83]:
X = np.random.random((10, 10))
X - np.mean(X, axis=0)

array([[-0.12691868,  0.08821236,  0.20868449,  0.16391315, -0.32168319,
         0.4370968 ,  0.05394031,  0.11043319,  0.42398341,  0.04104708],
       [ 0.20542462, -0.34687438, -0.26796295,  0.22233957, -0.30626528,
        -0.38052359,  0.1733967 ,  0.11742354, -0.23815465, -0.11124508],
       [-0.02510361,  0.1087724 , -0.10332643,  0.08885407, -0.02321901,
         0.45877874,  0.34754501,  0.27175382, -0.12864417,  0.34234515],
       [-0.07731242,  0.3447665 ,  0.37215695, -0.20263306,  0.16948011,
        -0.41263604, -0.40716461,  0.3095402 , -0.04178227, -0.44857098],
       [-0.19642004,  0.21356821, -0.29036069,  0.29462509, -0.03950136,
         0.38965599,  0.09408673, -0.45626057,  0.25715399, -0.46937642],
       [ 0.29881847,  0.0169122 , -0.39347026,  0.14716337, -0.16620618,
         0.35516577, -0.53786004, -0.51370662, -0.18594966,  0.21532765],
       [ 0.21641617, -0.00453204, -0.04352663,  0.11140972,  0.38292916,
        -0.13227788, -0.11301266,  0.23918408

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [86]:
X = np.random.normal(loc=5, scale=2., size=1000)
np.mean(X), np.var(X)

(5.038023074108321, 3.610403801928839)

**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [118]:
(np.arange(5) + np.arange(5).reshape(5,1)) % 5

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]], dtype=int32)