In [1]:
from sympy import *
import numpy as np

In [2]:
x, y, z = symbols('x, y, z')

Объявляем функцию

In [3]:
f = 2*x*x + 3.6*y*y + 4.6*z*z + x*y - y*z + x*z + x - 2*y + 3*z + 6
f

2*x**2 + x*y + x*z + x + 3.6*y**2 - y*z - 2*y + 4.6*z**2 + 3*z + 6

Подставляем в функцию точку (0, 0, 0).

In [4]:
args = {x:0, y:0, z:0}
f.subs(args)

6

Ответ 6. Все верно. Далее объявляем матрицы.

In [8]:
A = np.array([[2, 1, 1], [1, 3.6, -1], [1, -1, 4.6]])
B = np.array([1, -2, 3])
A, B

(array([[ 2. ,  1. ,  1. ],
        [ 1. ,  3.6, -1. ],
        [ 1. , -1. ,  4.6]]), array([ 1, -2,  3]))

In [ ]:
def get_point(x_list) -> dict:
    return {x: x_list[0], y: x_list[1], z: x_list[2]}

In [5]:
eps = 1e-6

Стартовая точка (0,0,0)

In [7]:
x_k = np.array([0, 0, 0])
f1 = f.subs({x: x_k[0], y: x_k[1], z: x_k[2]})
f1

6

Делаем нужные вычисления для МНГС. Где-то тут градиент, где-то еще одна херня :)

In [13]:
q = np.dot(A, x_k) + B
q

array([ 1., -2.,  3.])

In [18]:
q*q

array([1., 4., 9.])

In [17]:
(q*q).sum(axis = 0)

14.0

In [24]:
u = - (q*q).sum(axis=0) / np.dot(q, np.dot(A, q.T))
u

-0.19498607242339838

Пускаем все это дело в цикл

In [30]:
f_n = []
x_k = np.array([0, 0, 0])
while True:
    q = np.dot(A, x_k) + B
    u = - (q*q).sum(axis=0) / np.dot(q, np.dot(A, q.T))
    x_k = x_k + q*u
    f2 = f1
    f1 = f.subs({x:x_k[0], y:x_k[1], z:x_k[2]})
    f_n.append(f1)
    if abs(f1 - f2) < eps:
        break
f_n

[5.73386302092628,
 5.67554629207333,
 5.85153137089862,
 5.88119605470808,
 5.90282435291206,
 5.90402837187149,
 5.90803133235696,
 5.90757223370218,
 5.90941135720515,
 5.90921689250528,
 5.90999764416100,
 5.90991549377786,
 5.91024659226470,
 5.91021181686334,
 5.91035220865784,
 5.91033747447926,
 5.91039699983538,
 5.91039075464149,
 5.91041599247126,
 5.91041334496835,
 5.91042404531028,
 5.91042292288647,
 5.91042745960106,
 5.91042698372925]

В конце выводим значение функции на каждой итерации.